/**
 * Manual Content Generation API
 * Massachusetts Retirement System - On-Demand Blog Generation
 */

import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth/auth-config'
import { GeminiContentGenerator } from '@/lib/ai/gemini-content-generator'
import { ContentQualityChecker } from '@/lib/ai/content-quality-checker'
import { AICostTracker } from '@/lib/ai/ai-service-config'
import { getRandomTopic, MASSACHUSETTS_RETIREMENT_TOPICS } from '@/lib/ai/massachusetts-topics'
import { prisma } from '@/lib/prisma'
import { emailService } from '@/lib/email/email-service'

/**
 * POST /api/admin/blog/generate
 * Generate blog content on-demand
 */
export async function POST(request: NextRequest) {
  try {
    // Check authentication - either admin session or CRON secret
    const session = await getServerSession(authOptions)
    const authHeader = request.headers.get('authorization')
    const cronSecret = process.env.CRON_SECRET
    const isAuthorizedCron = cronSecret && authHeader === `Bearer ${cronSecret}`

    if (!isAuthorizedCron && !session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const {
      topic,
      category_id,
      ai_model = 'gemini-1.5-flash-latest',
      word_count = 1000,
      seo_keywords = [] as string[],
      auto_publish = false,
      template_id
    } = body

    // Validate required fields
    if (!topic) {
      return NextResponse.json(
        { error: 'Topic is required' },
        { status: 400 }
      )
    }

    // Estimate cost
    const estimatedCost = AICostTracker.estimateContentCost(word_count, ai_model)
    
    // Check budget
    const budgetCheck = await AICostTracker.checkBudget(estimatedCost, 'text_generation')
    if (!budgetCheck.allowed) {
      return NextResponse.json(
        { 
          error: 'Budget exceeded',
          details: budgetCheck.reason,
          remaining_budget: budgetCheck.remainingBudget
        },
        { status: 400 }
      )
    }

    console.log(`Generating content: ${topic} (Model: ${ai_model})`)

    // Generate content using Gemini AI (free)
    const contentGenerator = new GeminiContentGenerator()

    // Check if Gemini API is properly configured before proceeding
    if (!contentGenerator.isConfigured()) {
      console.error('Gemini API key not configured')
      return NextResponse.json(
        {
          error: 'AI service not configured',
          details: 'GEMINI_API_KEY environment variable is missing or invalid'
        },
        { status: 500 }
      )
    }

    console.log('Gemini API configuration validated, proceeding with content generation...')

    const generatedPost = await contentGenerator.generateContent({
      topic,
      category_id: category_id || '',
      ai_model: ai_model as any,
      target_word_count: word_count,
      seo_keywords: seo_keywords,
      template_id
    })

    // Assess content quality
    const qualityMetrics = await ContentQualityChecker.assessContentQuality(
      generatedPost.content,
      generatedPost.title
    )

    // Perform fact check
    const factCheckReport = await ContentQualityChecker.performFactCheck(generatedPost.content)

    // Calculate actual cost (simplified - would use actual token count in production)
    const actualCost = estimatedCost

    // Save blog post using specialized database client with retry logic
    let savedPost

    // Prepare blog post data (declare in higher scope for error logging)
    const blogPostData = {
        title: generatedPost.title,
        slug: generatedPost.slug || `${generatedPost.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').substring(0, 30)}-${crypto.randomUUID().substring(0, 8)}`,
        content: generatedPost.content,
        excerpt: generatedPost.meta_description || generatedPost.content.substring(0, 200),
        status: auto_publish && factCheckReport.overall_accuracy >= 80 ? 'published' : 'draft',
        publishedAt: auto_publish && factCheckReport.overall_accuracy >= 80 ? new Date() : undefined,
        isAiGenerated: true,
        aiModel: ai_model, // Fixed: was aiModelUsed, should be aiModel
        aiModelUsed: ai_model, // Keep both for compatibility
        aiGenerationPrompt: JSON.stringify(topic),
        aiGenerationCost: actualCost,
        contentQualityScore: qualityMetrics.overall_quality,
        factCheckStatus: factCheckReport.overall_accuracy >= 80 ? 'approved' : 'needs_review',
        autoGeneratedTags: generatedPost.keywords || [],
        seoTitle: generatedPost.title,
        seoDescription: generatedPost.meta_description || '',
        metaDescription: generatedPost.meta_description || '', // Fixed: added metaDescription field
        seoKeywords: generatedPost.keywords || [],
        authorId: session?.user?.id || null // Remove system user reference that may not exist
      }

    try {
      // Explicit logging to identify silent failure
      console.log('🔍 Attempting database save with data keys:', Object.keys(blogPostData))
      console.log('🔍 Blog post title:', blogPostData.title?.substring(0, 50))
      console.log('🔍 Blog post slug:', blogPostData.slug)

      // Retry mechanism for slug conflicts
      let attempts = 0
      const maxAttempts = 3

      while (attempts < maxAttempts) {
        try {
          // Use standard Prisma client with optimized connection string (prepared statement conflicts resolved)
          savedPost = await prisma.blogPost.create({ data: blogPostData })

          // Explicit success logging
          console.log('✅ Database save successful! Post ID:', savedPost.id)
          console.log('✅ Post title:', savedPost.title?.substring(0, 50))
          break // Success, exit retry loop

        } catch (slugError) {
          attempts++
          console.log(`⚠️  Attempt ${attempts} failed, trying new slug...`)

          if (slugError instanceof Error && slugError.message.includes('Unique constraint failed') && slugError.message.includes('slug')) {
            // Generate a new unique slug and retry
            blogPostData.slug = `${generatedPost.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').substring(0, 30)}-${crypto.randomUUID().substring(0, 8)}`
            console.log(`🔄 New slug generated: ${blogPostData.slug}`)

            if (attempts >= maxAttempts) {
              throw new Error(`Failed to create unique slug after ${maxAttempts} attempts`)
            }
          } else {
            // Different error, don't retry
            throw slugError
          }
        }
      }
    } catch (dbError) {
      console.warn('Database save failed, continuing with generated content:', dbError)
      // Type-safe error logging with detailed debugging
      const errorMessage = dbError instanceof Error ? dbError.message : String(dbError)
      console.warn('Database error details:', errorMessage)

      // Enhanced debugging for database storage issue
      console.warn('Database error type:', typeof dbError)
      console.warn('Database error name:', dbError instanceof Error ? dbError.name : 'Unknown')
      console.warn('Database error stack:', dbError instanceof Error ? dbError.stack : 'No stack trace')

      // Log the data that failed to save for debugging
      console.warn('Failed blog post data keys:', Object.keys(blogPostData))
      console.warn('Blog post data sample:', {
        title: blogPostData.title?.substring(0, 50),
        status: blogPostData.status,
        isAiGenerated: blogPostData.isAiGenerated,
        authorId: blogPostData.authorId
      })
      // Create a mock saved post for testing
      savedPost = {
        id: `test-${Date.now()}`,
        title: generatedPost.title,
        content: generatedPost.content,
        status: 'draft',
        created_at: new Date(),
        // Include error information for debugging
        _dbError: dbError instanceof Error ? dbError.message : String(dbError),
        _errorType: typeof dbError,
        _errorName: dbError instanceof Error ? dbError.name : 'Unknown'
      }
    }

    // Check for silent failure (savedPost is undefined)
    if (!savedPost) {
      console.warn('⚠️  Silent database failure detected - savedPost is undefined')
      savedPost = {
        id: `test-${Date.now()}`,
        title: generatedPost.title,
        content: generatedPost.content,
        status: 'draft',
        created_at: new Date(),
        // Include silent failure information
        _dbError: 'Silent failure - no exception thrown',
        _errorType: 'silent_failure',
        _errorName: 'SilentDatabaseFailure'
      }
    }

    // Record usage cost (with fallback for testing)
    try {
      await AICostTracker.recordUsage({
        date: new Date().toISOString().split('T')[0],
        service_provider: 'google',
        service_type: 'text_generation',
        tokens_used: Math.ceil(generatedPost.content.length / 4), // Rough estimate
        api_calls: 1,
        cost_usd: actualCost,
        post_id: savedPost.id
      })
    } catch (costError) {
      console.warn('Cost tracking failed, continuing:', costError)
    }

    console.log(`Content generated successfully: ${savedPost.id}`)

    // Send email notification for draft posts (only for real posts, not mock responses)
    let emailNotificationResult = null
    if (savedPost.status === 'draft' && !savedPost.id.startsWith('test-') && process.env.ENABLE_EMAIL === 'true') {
      try {
        console.log('📧 Sending email notification for draft blog post...')

        const reviewerEmails = process.env.CONTENT_REVIEWER_EMAILS?.split(',').map(email => email.trim()).filter(Boolean) || []

        if (reviewerEmails.length > 0 && emailService.isConfigured()) {
          const reviewUrl = `${process.env.NEXTAUTH_URL || 'https://www.masspension.com'}/admin/blog/review/${savedPost.id}`
          const postExcerpt = generatedPost.content.substring(0, 200) + '...'

          emailNotificationResult = await emailService.sendEmail({
            to: reviewerEmails,
            subject: `[Mass Pension] New Blog Draft Ready for Review: ${generatedPost.title}`,
            html: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <h2 style="color: #1e40af;">New Blog Post Draft Ready for Review</h2>

                <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
                  <h3 style="margin: 0 0 10px 0; color: #334155;">${generatedPost.title}</h3>
                  <p style="color: #64748b; margin: 0;"><strong>Post ID:</strong> ${savedPost.id}</p>
                  <p style="color: #64748b; margin: 5px 0;"><strong>Status:</strong> Draft</p>
                  <p style="color: #64748b; margin: 5px 0;"><strong>Word Count:</strong> ${generatedPost.content.split(/\s+/).length} words</p>
                </div>

                <div style="margin: 20px 0;">
                  <h4 style="color: #334155;">Content Preview:</h4>
                  <p style="color: #64748b; line-height: 1.6;">${postExcerpt}</p>
                </div>

                <div style="margin: 30px 0;">
                  <a href="${reviewUrl}" style="background: #1e40af; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Review & Approve Post</a>
                </div>

                <div style="margin: 20px 0; padding: 15px; background: #fef3c7; border-radius: 6px;">
                  <p style="margin: 0; color: #92400e;"><strong>Action Required:</strong> Please review this blog post draft and approve it for publication or request changes.</p>
                </div>

                <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">
                <p style="color: #94a3b8; font-size: 14px;">
                  This notification was sent by the Massachusetts Retirement System AI Blog Generation System.<br>
                  Generated on ${new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })} EST
                </p>
              </div>
            `,
            text: `
New Blog Post Draft Ready for Review

Title: ${generatedPost.title}
Post ID: ${savedPost.id}
Status: Draft
Word Count: ${generatedPost.content.split(/\s+/).length} words

Content Preview:
${postExcerpt}

Review URL: ${reviewUrl}

Action Required: Please review this blog post draft and approve it for publication or request changes.

This notification was sent by the Massachusetts Retirement System AI Blog Generation System.
Generated on ${new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })} EST
            `
          })

          if (emailNotificationResult.success) {
            console.log('✅ Email notification sent successfully to:', reviewerEmails.join(', '))
          } else {
            console.warn('❌ Email notification failed:', emailNotificationResult.error)
          }
        } else {
          console.warn('⚠️  Email notification skipped: No reviewer emails configured or email service not configured')
        }
      } catch (emailError) {
        console.error('❌ Email notification error:', emailError)
        emailNotificationResult = {
          success: false,
          error: emailError instanceof Error ? emailError.message : 'Unknown email error',
          provider: 'unknown',
          timestamp: new Date()
        }
      }
    }

    return NextResponse.json({
      success: true,
      post: {
        id: savedPost.id,
        title: savedPost.title,
        slug: savedPost.slug,
        status: savedPost.status,
        quality_score: qualityMetrics.overall_quality,
        fact_check_status: savedPost.factCheckStatus,
        word_count: generatedPost.content.split(/\s+/).length,
        cost: actualCost
      },
      quality_metrics: qualityMetrics,
      fact_check_report: factCheckReport,
      message: auto_publish && factCheckReport.overall_accuracy >= 80
        ? 'Content generated and published successfully'
        : 'Content generated and saved as draft for review',
      // Include database error information for debugging if post ID starts with 'test-'
      ...(savedPost.id?.startsWith('test-') && '_dbError' in savedPost && {
        debug_info: {
          database_error: (savedPost as any)._dbError,
          error_type: (savedPost as any)._errorType,
          error_name: (savedPost as any)._errorName,
          note: 'This is a mock response due to database save failure',
          mock_post_keys: Object.keys(savedPost)
        }
      }),
      // Always include if it's a test post for debugging
      ...(savedPost.id?.startsWith('test-') && {
        is_mock_response: true,
        database_save_failed: true
      }),
      // Include email notification result
      ...(emailNotificationResult && {
        email_notification: {
          sent: emailNotificationResult.success,
          error: emailNotificationResult.error,
          provider: emailNotificationResult.provider,
          timestamp: emailNotificationResult.timestamp
        }
      })
    })

  } catch (error) {
    console.error('Content generation error:', error)
    return NextResponse.json(
      { 
        error: 'Content generation failed',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

/**
 * GET /api/admin/blog/generate/topics
 * Get available topics for content generation
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const category = searchParams.get('category')
    const complexity = searchParams.get('complexity') as 'beginner' | 'intermediate' | 'advanced' | null
    const group = searchParams.get('group') as 'Group 1' | 'Group 2' | 'Group 3' | 'Group 4' | null
    const seasonal = searchParams.get('seasonal') === 'true'

    let topics = MASSACHUSETTS_RETIREMENT_TOPICS

    // Apply filters
    if (category) {
      topics = topics.filter(topic => topic.category === category)
    }

    if (complexity) {
      topics = topics.filter(topic => topic.complexity_level === complexity)
    }

    if (group) {
      topics = topics.filter(topic => topic.target_groups.includes(group))
    }

    if (seasonal) {
      const currentMonth = new Date().toLocaleString('default', { month: 'long' })
      topics = topics.filter(topic => 
        topic.seasonal_relevance?.includes(currentMonth)
      )
    }

    // Get categories for filtering
    const categories = [...new Set(MASSACHUSETTS_RETIREMENT_TOPICS.map(t => t.category))]
    
    // Get complexity levels
    const complexityLevels = [...new Set(MASSACHUSETTS_RETIREMENT_TOPICS.map(t => t.complexity_level))]

    // Get target groups
    const targetGroups = [...new Set(MASSACHUSETTS_RETIREMENT_TOPICS.flatMap(t => t.target_groups))]

    return NextResponse.json({
      topics,
      filters: {
        categories,
        complexity_levels: complexityLevels,
        target_groups: targetGroups
      },
      total: topics.length
    })

  } catch (error) {
    console.error('Error fetching topics:', error)
    return NextResponse.json(
      { error: 'Failed to fetch topics' },
      { status: 500 }
    )
  }
}


