/**
 * TypeScript types for AI Blog System
 * Massachusetts Retirement System - Automated Content Generation
 */

export interface BlogPost {
  id: string
  title: string
  slug: string
  content: string
  excerpt?: string
  featuredImageUrl?: string
  authorId?: string
  publishedAt?: string
  createdAt: string
  updatedAt: string
  status: 'draft' | 'published' | 'archived'
  viewCount: number
  seoTitle?: string
  seoDescription?: string
  seoKeywords?: string[]

  // AI-specific fields
  isAiGenerated: boolean
  aiModelUsed?: string
  aiGenerationPrompt?: string
  aiGenerationCost?: number
  contentQualityScore?: number
  factCheckStatus: 'pending' | 'approved' | 'needs_review' | 'rejected'
  scheduledPublishAt?: string
  autoGeneratedTags?: string[]
  internalLinksAdded: boolean
  seoOptimized: boolean
}

export interface BlogCategory {
  id: string
  name: string
  slug: string
  description?: string
  color: string
  icon?: string
  sort_order: number
  is_ai_topic: boolean
  created_at: string
}

export interface BlogPostCategory {
  id: string
  post_id: string
  category_id: string
  created_at: string
}

export interface AIContentJob {
  id: string
  job_type: 'scheduled_post' | 'topic_research' | 'content_update' | 'seo_optimization'
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'
  topic: string
  category_id?: string
  target_publish_date?: string
  ai_model: string
  generation_prompt?: string
  generated_post_id?: string
  error_message?: string
  cost_estimate?: number
  actual_cost?: number
  execution_time_seconds?: number
  created_at: string
  started_at?: string
  completed_at?: string
  created_by?: string
}

export interface ContentReview {
  id: string
  postId: string
  reviewerId?: string
  reviewStatus: 'pending' | 'approved' | 'needs_changes' | 'rejected'
  reviewNotes?: string
  factCheckCompleted: boolean
  seoCheckCompleted: boolean
  contentQualityRating?: number
  suggestedChanges?: string
  reviewedAt: string
  createdAt: string
}

export interface AIContentTemplate {
  id: string
  name: string
  description?: string
  categoryId?: string
  templateType: 'blog_post' | 'newsletter' | 'guide' | 'update'
  systemPrompt: string
  userPromptTemplate: string
  expectedWordCount: number
  seoFocusKeywords?: string[]
  internalLinkTargets?: string[]
  isActive: boolean
  usageCount: number
  averageQualityScore?: number
  createdAt: string
  updatedAt: string
}

export interface BlogAnalytics {
  id: string
  post_id: string
  date: string
  page_views: number
  unique_visitors: number
  time_on_page_seconds: number
  bounce_rate?: number
  social_shares: number
  calculator_clicks: number
  adsense_revenue?: number
  created_at: string
}

export interface AIUsageCost {
  id: string
  date: string
  service_provider: 'openai' | 'anthropic' | 'stability' | 'google'
  service_type: 'text_generation' | 'image_generation' | 'fact_checking'
  tokens_used?: number
  api_calls: number
  cost_usd: number
  post_id?: string
  job_id?: string
  created_at: string
}

// Extended types with relations
export interface BlogPostWithCategories extends BlogPost {
  categories: BlogCategory[]
  reviews?: ContentReview[]
  analytics?: BlogAnalytics[]
}

export interface BlogCategoryWithPosts extends BlogCategory {
  posts: BlogPost[]
  postCount: number
}

export interface AIContentJobWithDetails extends AIContentJob {
  category?: BlogCategory
  generatedPost?: BlogPost
  costBreakdown?: AIUsageCost[]
}

// Content generation request types
export interface ContentGenerationRequest {
  topic: {
    title: string
    description?: string
    keywords?: string[]
  }
  categoryId: string
  templateId?: string
  targetWordCount?: number
  wordCount?: number
  targetAudience?: string
  contentType?: string
  additionalContext?: string
  seoKeywords?: string[]
  targetPublishDate?: string
  aiModel?: 'gpt-4' | 'gpt-3.5-turbo' | 'claude-3-opus' | 'claude-3-sonnet' | 'gemini-1.5-pro'
  includeImages?: boolean
  autoPublish?: boolean
}

export interface ContentGenerationResponse {
  id: string
  title: string
  slug: string
  content: string
  excerpt: string
  metaDescription: string
  keywords: string[]
  wordCount: number
  readingTime: number
  aiModel: string
  generationTime: string
  costEstimate: number
  qualityScore: number
  seoOptimized: boolean
  factChecked: boolean
  status: 'queued' | 'processing' | 'completed' | 'failed'
  autoGeneratedTags: string[]
  seoTitle: string
  seoDescription: string
  seoKeywords: string
}

// Massachusetts-specific content types
export interface MassachusettsRetirementTopic {
  id: string
  title: string
  description: string
  category: string
  keywords: string[]
  targetGroups: ('Group 1' | 'Group 2' | 'Group 3' | 'Group 4')[]
  complexityLevel: 'beginner' | 'intermediate' | 'advanced'
  seasonalRelevance?: string[]
  relatedCalculators: string[]
  officialSources: string[]
}

// Content quality metrics
export interface ContentQualityMetrics {
  readabilityScore: number
  seoScore: number
  factAccuracyScore: number
  engagementPotential: number
  massachusettsRelevance: number
  overallQuality: number
  improvementSuggestions: string[]
}

// AI service configuration
export interface AIServiceConfig {
  provider: 'openai' | 'anthropic' | 'stability' | 'google'
  model: string
  api_key: string
  max_tokens?: number
  temperature?: number
  cost_per_token?: number
  rate_limit?: {
    requests_per_minute: number
    tokens_per_minute: number
  }
}

// Content scheduling types
export interface ContentSchedule {
  id: string
  name: string
  description?: string
  frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly'
  day_of_week?: number
  day_of_month?: number
  time_of_day: string
  categories: string[]
  is_active: boolean
  next_execution: string
  last_execution?: string
}

// Blog management dashboard types
export interface BlogDashboardStats {
  total_posts: number
  ai_generated_posts: number
  pending_reviews: number
  scheduled_posts: number
  monthly_views: number
  monthly_adsense_revenue: number
  ai_costs_this_month: number
  top_performing_posts: BlogPost[]
  recent_ai_jobs: AIContentJob[]
}

// Content approval workflow
export interface ApprovalWorkflow {
  post_id: string
  current_step: 'ai_generation' | 'fact_check' | 'seo_review' | 'content_review' | 'final_approval'
  steps_completed: string[]
  assigned_reviewers: string[]
  deadline?: string
  priority: 'low' | 'medium' | 'high'
  notes: string[]
}

// SEO optimization types
export interface SEOOptimization {
  target_keywords: string[]
  meta_title: string
  meta_description: string
  internal_links: {
    anchor_text: string
    target_url: string
    context: string
  }[]
  external_links: {
    anchor_text: string
    target_url: string
    domain: string
  }[]
  readability_improvements: string[]
  keyword_density: Record<string, number>
}

// Image generation types
export interface ImageGenerationRequest {
  prompt: string
  style: 'professional' | 'infographic' | 'illustration' | 'photo'
  dimensions: '1024x1024' | '1792x1024' | '1024x1792'
  post_id?: string
  alt_text: string
}

export interface GeneratedImage {
  id: string
  url: string
  alt_text: string
  prompt_used: string
  style: string
  dimensions: string
  cost: number
  created_at: string
}

// Error handling types
export interface AIServiceError {
  code: string
  message: string
  details?: Record<string, any>
  retry_after?: number
  cost_incurred?: number
}

// Fact-checking types
export interface FactCheckResult {
  claim: string
  verification_status: 'verified' | 'disputed' | 'unverified' | 'false'
  sources: string[]
  confidence_score: number
  notes?: string
}

export interface FactCheckReport {
  post_id: string
  claims_checked: FactCheckResult[]
  overall_accuracy: number
  flagged_content: string[]
  recommended_changes: string[]
  checked_at: string
  checker_id?: string
}
