/**
 * Blog Posts API
 * Massachusetts Retirement System - Blog Content Management
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth/auth-config'
import { BlogPost, BlogCategory } from '@/types/ai-blog'

/**
 * GET /api/blog/posts
 * Get published blog posts with filtering and pagination
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    
    // Parse query parameters
    const category = searchParams.get('category')
    const search = searchParams.get('search')
    const aiGenerated = searchParams.get('ai_generated')
    const status = searchParams.get('status') || 'published'
    const limit = parseInt(searchParams.get('limit') || '20')
    const offset = parseInt(searchParams.get('offset') || '0')
    const sortBy = searchParams.get('sort') || 'publishedAt'
    const sortOrder = searchParams.get('order') || 'desc'

    // Build where clause
    const where: any = {}

    // If status explicitly provided (and not 'all'), filter by it; otherwise default to published for public
    if (status && status !== 'all') {
      where.status = status as 'published' | 'draft' | 'archived'
    } else {
      where.status = 'published'
    }

    // If requesting drafts or all, require admin session
    if ((status === 'draft' || status === 'all') && !(await getServerSession(authOptions))?.user) {
      return NextResponse.json({ error: 'Unauthorized to view drafts' }, { status: 401 })
    }

    // Filter by AI generated content
    if (aiGenerated !== null) {
      where.isAiGenerated = aiGenerated === 'true'
    }

    // Search functionality
    if (search) {
      where.OR = [
        { title: { contains: search, mode: 'insensitive' } },
        { content: { contains: search, mode: 'insensitive' } },
        { excerpt: { contains: search, mode: 'insensitive' } },
        { seoKeywords: { has: search } }
      ]
    }

    // Category filtering
    let categoryFilter = {}
    if (category && category !== 'all') {
      categoryFilter = {
        categories: {
          some: {
            category: {
              slug: category
            }
          }
        }
      }
    }

    // Check if prisma is available (might be null during build time)
    if (!prisma) {
      return NextResponse.json({
        success: true,
        posts: [],
        pagination: {
          page: 1,
          limit: 10,
          total: 0,
          totalPages: 0
        }
      })
    }

    // Fetch posts with relations
    const posts = await prisma.blogPost.findMany({
      where: {
        ...where,
        ...categoryFilter
      },
      include: {
        categories: {
          include: {
            category: true
          }
        },
        reviews: {
          where: {
            reviewStatus: 'approved'
          },
          orderBy: {
            createdAt: 'desc'
          },
          take: 1
        }
      },
      orderBy: {
        [sortBy]: sortOrder as 'asc' | 'desc'
      },
      take: limit,
      skip: offset
    })

    // Get total count for pagination
    const totalCount = await prisma.blogPost.count({
      where: {
        ...where,
        ...categoryFilter
      }
    })

    // Transform to match our types
    const transformedPosts: BlogPost[] = posts.map(post => ({
      id: post.id,
      title: post.title,
      slug: post.slug,
      content: post.content,
      excerpt: post.excerpt || undefined,
      featured_image_url: post.featuredImageUrl || undefined,
      author_id: post.authorId || undefined,
      published_at: post.publishedAt?.toISOString() || undefined,
      created_at: post.createdAt.toISOString(),
      updated_at: post.updatedAt.toISOString(),
      status: post.status as 'draft' | 'published' | 'archived',
      view_count: post.viewCount,
      seo_title: post.seoTitle || undefined,
      seo_description: post.seoDescription || undefined,
      seo_keywords: post.seoKeywords || undefined,
      is_ai_generated: post.isAiGenerated,
      ai_model_used: post.aiModelUsed || undefined,
      ai_generation_prompt: post.aiGenerationPrompt || undefined,
      ai_generation_cost: post.aiGenerationCost ? parseFloat(post.aiGenerationCost.toString()) : undefined,
      content_quality_score: post.contentQualityScore || undefined,
      fact_check_status: post.factCheckStatus as 'pending' | 'approved' | 'needs_review' | 'rejected',
      scheduled_publish_at: post.scheduledPublishAt?.toISOString() || undefined,
      auto_generated_tags: post.autoGeneratedTags || undefined,
      internal_links_added: post.internalLinksAdded,
      seo_optimized: post.seoOptimized
    }))

    return NextResponse.json({
      posts: transformedPosts,
      pagination: {
        total: totalCount,
        limit,
        offset,
        has_more: offset + limit < totalCount,
        page: Math.floor(offset / limit) + 1,
        total_pages: Math.ceil(totalCount / limit)
      },
      filters: {
        category,
        search,
        ai_generated: aiGenerated,
        status,
        sort_by: sortBy,
        sort_order: sortOrder
      }
    })

  } catch (error) {
    console.error('Error fetching blog posts:', error)
    // Harden API: return 200 with empty posts so frontend can gracefully fallback
    return NextResponse.json({
      posts: [],
      pagination: {
        total: 0,
        limit: 0,
        offset: 0,
        has_more: false,
        page: 1,
        total_pages: 0
      },
      error: 'upstream_error',
    })
  }
}




