import type { MetadataRoute } from "next"

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/calculator",
        "/wizard",
        "/blog",
        "/resources",
        "/faq",
        "/about",
        "/contact",
        "/pricing",
        "/social-security",
        "/guides",
        "/checklist",
        "/methodology",
        "/benefits",
        "/tax-bomb",
        "/ssfa-auditor",
        "/financial-literacy",
        "/teachers",
      ],
      disallow: [
        "/api/",
        "/admin/",
        "/dev/",
        "/debug/",
        "/debug-select/",
        "/_next/",
        "/auth/",
        "/auth/signin",
        "/auth/signup",
        "/auth/signout",
        "/account/",
        "/dashboard/",
        "/profile/",
        "/billing/",
        "/subscription/",
        "/api/auth/",
        "/api/calculations/",
        "/api/debug/",
        "/api/health/",
        "/api/newsletter/",
        "/api/pdf/",
        "/api/pension-calculation/",
        "/api/profile/",
        "/api/retirement/",
        "/api/stripe/",
        "/api/subscription/",
        "/api/test*",
        "/api/email/",
      ],
    },
    sitemap: "https://www.masspension.com/sitemap.xml",
  }
}
